rvm:
  - 1.8.7
  - 1.9.3

before_script: "./spec/ci/before_script"

script: "./spec/ci/script"

env:
  - RADIANT_VERSION=1.1.3 DB=mysql
  - RADIANT_VERSION=1.1.3 DB=postgres
  - RADIANT_VERSION=master DB=mysql
  - RADIANT_VERSION=master DB=postgres

notifications:
  recipients:
    - sipple@trustarts.org
